server.port=10000
spring.application.name=core-wallet-service

# Point your code directly to clear environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

gemini.api-key=${GEMINI_API_KEY}
services.ml-analytics.url=${SERVICES_ML_ANALYTICS_URL}


#AQ.Ab8RN6KJMBNn1gxi0CIVOL7KkaYMf8BTgIplotKjzyNteVnP-A