server.port=10000
spring.application.name=core-wallet-service

# Using completely custom placeholders to prevent Render from hijacking the connection
spring.datasource.url=${SECURE_MAPPING_URL}
spring.datasource.username=${SECURE_MAPPING_USER}
spring.datasource.password=${SECURE_MAPPING_PWD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

gemini.api-key=${GEMINI_API_KEY}
services.ml-analytics.url=${SERVICES_ML_ANALYTICS_URL}


#AQ.Ab8RN6KJMBNn1gxi0CIVOL7KkaYMf8BTgIplotKjzyNteVnP-A